### ISSUE TITLE
Lists sites running specific code assets 

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/lil_shrugger#107]
Until we have https://github.com/CuBoulder/express/issues/1156, the queries required to figure out which sites are running which code assets require querying the sites object vs. the statistic object.  Currently, we don't have any way to expose this other than the default Eve XML output.

Since the code asset ids can change, this would also benefit from being dynamic.

I would like a link on code.html to the results of queries like...

https://osr-atlas03.int.colorado.edu/sites?where={%22code.package%22:%22591def5f926f5b28e7361dc8%22} - 4 sites running Digital Campaign Bundle 

https://osr-atlas03.int.colorado.edu/sites?where={%22code.package%22:%22592eee80926f5b1ca774ec42%22} - 18 sites running Content Sequence Bundle 

https://osr-atlas03.int.colorado.edu/sites?where={%22code.package%22:%22592eeea5926f5b1c3fc39886%22} - 15 sites running Collections Bundle

**Comment by alexfinnarn** [comment]
This already is kind of done on the sites listing page, index.html. 

![screen shot 2017-07-19 at 10 05 37 am](https://user-images.githubusercontent.com/3640707/28377416-e730aaba-6c69-11e7-8bd1-0ce945b56d90.png)

All of those queries can be done and return the same number of sites as listed above. You might have to use more of the bundle name, e.g. "express_collections" (15 results) instead of just "collections" (16 results). 

#95 will be an attempt at making the filter smarter, and you could also make it so only the visible columns are searched.
