### ISSUE TITLE
Fix package updates

### ISSUE THREAD

**Issue by owenmorrill** [CuBoulder/lil_shrugger#128]

**Comment by alexfinnarn** [comment]
I think this part could go to the Sites page. Essentially, you are searching for sites based on a query and then selecting code, profile, and/or bundles from select lists. 

https://www.colorado.edu/webcentral/admin/tools/sites/update

The select lists and checkboxes should be converted into an autocomplete field that adds the code to a text area where you can click to remove what is there already. 

The tricky part is how you add or remove the code from sites that have different combinations of code. I think enforcing only one code change per package update makes sense since the Atlas query will probably be about which sites have certain bundles enabled. 

Resolving this issue goes hand in hand with #95 since the current filter on the data table can generally get you all the sites using a certain bundle if you type in the exact name of the bundle in question.

**Comment by alexfinnarn** [comment]
To do this more quickly, I think it is better to put in in a separate "Packages" route like it was set up in the dev branch.
