### ISSUE TITLE
Add update group to filter options

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/lil_shrugger#205]

**Comment by kreynen** [comment]
I'm not sure if this requires piping the group to stats or it can be easily added to the site record keys, but we want to be able to throw a message on the next page load for all authenticated users that their update group is next from Shrugger.

**Comment by kreynen** [comment]
> Adding a key to the data table for the Sites page would be trivial.

Let's do this then.  While we could create redundant data in stats, it would be stale.

No need to relay or change data... just use it to execute a command on a sub-set of sites.

**Comment by alexfinnarn** [comment]
I attempted adding the key to the filter table http://live-shrugger-8.pantheonsite.io/shrugger/?filter=group:1, but since the groups are numbered 1,2,3 instead of 01,02,03 group:1 gives you both 1 and 1*. 

So, the best and only way to get exact results for groups is via the settings.html "Sites Query" variable.

**Comment by alexfinnarn** [comment]
update_group has been added to both the 1.x and dev branches. The expression search will allow for exact matching without having to change the Sites Query on the settings page.
