### ISSUE TITLE
Alter homepage P1 to make it less likely someone will think it's a P1

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/lil_shrugger#228]
The homepages have a different pool in the site record <pool>poolb-homepage</pool>

![lil__shrugger](https://user-images.githubusercontent.com/385234/35307697-3553c43a-0061-11e8-9ff0-f0b3c6de9d6e.png)

**Comment by alexfinnarn** [comment]
I added a PR that kind of works. https://osr-atlas03.int.colorado.edu/atlas/statistics?where={%22variable_theme_default%22:%22homepage2017_theme%22} is the query that will always return one site for now while the homepage theme is called that.

The problem is that the default theme variable is in the stats record and not the site record. So, storing the path isn't as easy as what I set up in the PR if you have to match a site record ID to the site with the homepage theme and then store that P1 to check later on display.

**Comment by alexfinnarn** [comment]
https://osr-atlas03.int.colorado.edu/atlas/sites?where=%7B%22type%22:%22express%22,%22f5only%22:false,%22pool%22:%22poolb-homepage%22%7D should be the query used. So, f5only and pool should be enough to target the link.
