### ISSUE TITLE
Site delete works inconsistently

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/lil_shrugger#355]
I've successfully deleted sites in the past, but using new-test-shrugger-8 on Pantheon today I've tried to post a delete to prod using Shrugger and had nothing happen.  No error.  I don't even see a network request in Chrome's network tools.  Not sure if it's related to searching for the site first or this is bug deleting any site in any environment.

Deleting code objects has been working fine.

**Comment by alexfinnarn** [comment]
Probably https://github.com/CuBoulder/lil_shrugger/blob/1.x/src/pages/Sites.vue#L160. 

It is better to remove event listeners when possible, but in many cases, removing the listeners does more harm than good. 

Initially, that was put in because certain events were being listened to twice. When the component is mounted the events are listened to, when the component is destroyed the event listeners are removed.  

I think mounting doesn't re-add the event listeners for some reason, but I imagine this happens when switching between the Sites and Code pages which mounts and destroys the Code component.

The best way to debug this issue is to add logging to events. Since they are all sent via the `bus` Vue instance, the `emit()` method can be modified to log all of the events.

**Comment by alexfinnarn** [comment]
Actually, the callbacks for the confirm button confirmation should be more specific. If that happens, then the events can't fire twice like they do sometimes now since two components listen for the same event.

**Comment by alexfinnarn** [comment]
Turn https://github.com/CuBoulder/lil_shrugger/blob/1.x/src/components/RowEdit.vue#L53 into `deleteCallback` and the update one `updateCallback`.
