### ISSUE TITLE
Deletes can now delete more than 1 site

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/lil_shrugger#362]
I think this is related to the change for https://github.com/CuBoulder/lil_shrugger/issues/355

I intended to delete https://osr-atlas03.int.colorado.edu/atlas/sites/5aa10a19926f5b69cab9f7a6 and https://osr-atlas03.int.colorado.edu/atlas/sites/5a593e8a926f5b2db8cca823, but not today

> {
>   "_index": "logstash-access-2018.06.14",
>   "_type": "access",
>   "_id": "AWP_MaMFqCMw-YzBuEky",
>   "_score": null,
>   "_source": {
>     "@version": "1",
>     "@timestamp": "2018-06-14T16:47:10.000Z",
>     "path": "/data/web/logs/osr-atlas03.int.colorado.edu-access_log",
>     "host": "osr-atlas03.int.colorado.edu",
>     "type": "access",
>     "environment": "production",
>     "clientip": "128.138.79.119",
>     "ident": "-",
>     "auth": "-",
>     "verb": "DELETE",
>     "request": "/atlas/sites/589b493e926f5b53900a6443",
>     "httpversion": "1.1",
>     "response": "412",
>     "bytes": "93",
>     "referrer": "\"http://localhost:8057/\"",
>     "tags": [
>       "grok_parse",
>       "tmatch",
>       "tmatch",
>       "agent_parse"
>     ],
>     "useragent": {
>       "name": "Chrome",
>       "os": "Mac OS X 10.12.6",
>       "os_name": "Mac OS X",
>       "os_major": "10",
>       "os_minor": "12",
>       "device": "Other",
>       "major": "67",
>       "minor": "0",
>       "patch": "3396"
>     }
>   },
> }
> {
>   "_index": "logstash-access-2018.06.14",
>   "_type": "access",
>   "_id": "AWP_MaMFqCMw-YzBuEkw",
>   "_score": null,
>   "_source": {
>     "@version": "1",
>     "@timestamp": "2018-06-14T16:47:10.000Z",
>     "path": "/data/web/logs/osr-atlas03.int.colorado.edu-access_log",
>     "host": "osr-atlas03.int.colorado.edu",
>     "type": "access",
>     "environment": "production",
>     "clientip": "128.138.79.119",
>     "ident": "-",
>     "auth": "-",
>     "verb": "DELETE",
>     "request": "/atlas/sites/589b493e926f5b53900a6443",
>     "httpversion": "1.1",
>     "response": "412",
>     "bytes": "93",
>     "referrer": "\"http://localhost:8057/\"",
>     "tags": [
>       "grok_parse",
>       "tmatch",
>       "tmatch",
>       "agent_parse"
>     ],
>     "useragent": {
>       "name": "Chrome",
>       "os": "Mac OS X 10.12.6",
>       "os_name": "Mac OS X",
>       "os_major": "10",
>       "os_minor": "12",
>       "device": "Other",
>       "major": "67",
>       "minor": "0",
>       "patch": "3396"
>     }
>   },
> }
> {
>   "_index": "logstash-access-2018.06.14",
>   "_type": "access",
>   "_id": "AWP_MaMFqCMw-YzBuEkw",
>   "_score": null,
>   "_source": {
>     "@version": "1",
>     "@timestamp": "2018-06-14T16:47:10.000Z",
>     "path": "/data/web/logs/osr-atlas03.int.colorado.edu-access_log",
>     "host": "osr-atlas03.int.colorado.edu",
>     "type": "access",
>     "environment": "production",
>     "clientip": "128.138.79.119",
>     "ident": "-",
>     "auth": "-",
>     "verb": "DELETE",
>     "request": "/atlas/sites/589b493e926f5b53900a6443",
>     "httpversion": "1.1",
>     "response": "412",
>     "bytes": "93",
>     "referrer": "\"http://localhost:8057/\"",
>     "tags": [
>       "grok_parse",
>       "tmatch",
>       "tmatch",
>       "agent_parse"
>     ],
>     "useragent": {
>       "name": "Chrome",
>       "os": "Mac OS X 10.12.6",
>       "os_name": "Mac OS X",
>       "os_major": "10",
>       "os_minor": "12",
>       "device": "Other",
>       "major": "67",
>       "minor": "0",
>       "patch": "3396"
>     }
>   },
> }

**Comment by alexfinnarn** [comment]
The `deleteSiteRecord` event is only emitted one time as far as I can tell, but the `sites.update()` function is called for as many rows as the user viewed once the application has initialized.  

I haven't seen this happen consistently, but it always seems to happen if I click "Delete" but don't "Fire!" the request. If I don't click the confirm button for "Delete", then I only see one delete request being sent to the correct site. 

Ideally, the components activated by viewing a row would be destroyed when the row is hidden. 

There is a `v-show` used instead of a `v-if` for loading the row components, and `v-if` completely destroys and remounts the components. So, using `v-if` should "fix" this issue. 

However, I tried to use `v-if` originally and data for the components wasn't being loaded into the forms. Using `v-show` everything seemed fine until this issue popped up. 

There are two potential solutions:

1. Use `v-if` instead of `v-show`. Fixing it this way would be cleaner since it is a binary on/off for the component and its state. However, I remember this being a PITA and a fingers-crossed when it worked. On a first go, it doesn't work at all. I can't see rows or hide them probably due to event listeners not being there when the row is viewed because the component hasn't been created.

2. Destroy or re-render the components activated by viewing a row. This method is messier, and I have no idea how to do it at this point. I tried undrawing/re-drawing on `vm.$nextTick()` as well as `vm.$forceUpdate()` on the main Vue instance. Forcing an update is supposed to make the whole app refresh, but that doesn't work with what I've tried.

**Comment by alexfinnarn** [comment]
I did a spot test and using `v-if` did reset the confirm button's state while `v-show` didn't. So, solution one is the best idea to try out more. It's not as simple as just changing the directive, though.

**Comment by alexfinnarn** [comment]
One other point to note is that Webpack does "hot" module reloading when files are changed. I've noticed that Webpack doesn't reload the page cleanly. I think event listeners and other things are orphaned in the DOM and not garbage collected via the Virtual DOM. 

https://vue-loader.vuejs.org/guide/hot-reload.html

**Comment by alexfinnarn** [comment]
The issue, I think, is that the `deleteSiteRecord` event was called `deleteRecord` when trying to remove it. I changed the name and added removal of the events back in on component destroy.

**Comment by kreynen** [comment]
One fix would be to display a confirmation on the delete similar to the commands.  Commands can also get run twice, but when that happens I get duplicate confirmations.  Usually one says it's going to run the command on X number of sites with the query and then another confirmation that it's going to run on 0 sites with the same query.    When I look in Kibana, the commands are only being run once.

Delete currently just changes the button from Delete/Fire and then displays "You have sent a DELETE request to a site record. Site ID: XXXXX".  The assumption being that it is only going to send a payload for the site described above what you are looking at, but can't this be confirmed before a DELETE patch is sent?  

One way to confuse Vue is opening the details of a row using the eye icon and then searching or refreshing.  

You can end up with values in the form other than the values for the only site in the results.  Clicking the eye again for a different row may or may not change the values.  In some situations, it closes the details.  In others it reloads it.

It's also possible to end up carrying around an open detail at the bottom of the form that doesn't match anything in the current filtered list.

![screen shot 2018-06-15 at 9 33 07 am](https://user-images.githubusercontent.com/385234/41476852-f2ff21da-707f-11e8-8e07-2ed3daf90db0.png)

One option would be to change the design pattern so that instead of attempting to load the form under the row that may or not still be there if other actions are taken like searching or filtering, open the details in a modal so that no other actions can be taken while that specific site or code record is open.  

![screen shot 2018-06-15 at 9 02 54 am](https://user-images.githubusercontent.com/385234/41476077-b54c1fde-707d-11e8-8e37-a320e0643c7f.png)

**Comment by alexfinnarn** [comment]
There is a PR to add warning messages as well as #418 to move the edit screen to only load on a separate route.
