### ISSUE TITLE
Changing output for exportSiteIdentikeys

### ISSUE THREAD

**Issue by anniebyellow13** [CuBoulder/lil_shrugger#387]
Currently running an export of all site Identikeys in the Prod environment shows those Identikeys in a comma delimited list. Sales Force needs the Identikeys such that each on is on its own row. I would like to request that the export read:

Identikey
Identikey
Identikey 

rather than:

Identikey, Identikey, Identikey

Thank you!

**Comment by alexfinnarn** [comment]
I think this would be best accomplished by adding an "export delimiter" to the Settings options so that `\n` or `,` could be used.

I actually can't find where the comma is inserted with a quick through the code. For now, I would use https://delim.co/. Put the comma list on the right, arrow it to the left, and you're good to go.
